### ISSUE TITLE
Enhancement:  Add "Comment" as a valid field to any config json object 

### ISSUE THREAD

**Issue by pvarga** [vesposito/easyucs#1]
As the configurations get more complex, it is helpful to document the rationale for a config selection right there in the json.  Unfortunately, JSON does not permit line or block comments like XML or YAML.  So, could we teach EasyUCS to permit "Comment" fields on any object?

Thanks!  And great work!  This tool is absolutely AWESOME!

**Comment by vesposito** [comment]
This is a good idea indeed. I could easily add support for a "comment" field for each object directly in the JSON schema, so that such a field is allowed when importing a config, without changing anything in the code (which would essentially mean that this field is ignored).

Thanks for the feedback by the way, let us know if you have other ideas/improvements or suggestions!

**Comment by vesposito** [comment]
Added support for "comment" fields in version 0.9.4
